import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  docsSidebar:  [
    {
      type: 'category',
      label: 'Get started',
      description: 'Your introduction to the Rune language.',
      customProps: {
        icon: '/img/rune/icon/Rune-icon-Get-started.png',
      },
      link: {
        type: 'generated-index',
        title: 'Get started',
        description: 'Your introduction to the Rune language.',
        slug: '/get-started',
      },
      items: [
        {
                  type: 'doc',
                  id: 'get-started/introducing-rune',
                  customProps: {
                    icon: '/img/rune/icon/2024_Rune_Icon.png',
                  },
                },
        {
          type: 'doc',
          id: 'get-started/rune-keywords',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-Keyword-search.png',
          },
        },
        {
          type: 'doc',
          id: 'get-started/overview',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-Overview.png',
          },
        },
      ],
    },
    {
      type: 'category',
      label: 'Modelling components',
      description: 'Our components and how they work, with examples.',
      customProps: {
        icon: '/img/rune/icon/Rune-icon-Components.png',
      },
      link: {
        type: 'generated-index',
        title: 'Modelling components',
        description: 'The Rune DSL can express eight types of model components. This documentation details the purpose and features of each type of model component and highlights their relationships.',
        slug: '/modelling-components',
      },
      items: [
        'modelling-components/data',
        'modelling-components/metadata',
        'modelling-components/expressions',
        'modelling-components/data-validation',
        'modelling-components/function',
        'modelling-components/mapping',
        'modelling-components/namespace',
        'modelling-components/reporting',
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      description: 'Advanced use of Rune and how you can contribute.',
      customProps: {
        icon: '/img/rune/icon/Rune-icon-Developers.png',
      },
      link: {
        type: 'generated-index',
        title: 'Developers',
        description: 'Advanced use of Rune and how you can contribute.',
        slug: '/developers',
      },
      items: [
        {
          type: 'doc',
          id: 'developers/rune-and-java',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-Rune-and-Java.png',
          },
        },
        {
          type: 'doc',
          id: 'developers/code-generator',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-code-generator.png',
          },
        },
        {
          type: 'doc',
          id: 'developers/contribute-to-rune',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-contribute-to-Rune.png',
          },
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      description: 'Our FAQs, glossary, and find out how to get in touch.',
      customProps: {
        icon: '/img/rune/icon/Rune-icon-Resources.png',
      },
      link: {
        type: 'generated-index',
        title: 'Resources',
        description: 'Our FAQs, glossary, and find out how to get in touch.',
        slug: '/resources',
      },
      items: [
        {
          type: 'doc',
          id: 'resources/faqs',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-FAQs.png',
          },
        },
        {
          type: 'link',
          href: '/docs/resources/glossary',
          label: 'Glossary',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-Glossary.png',
          },
        },
        {
          type: 'doc',
          id: 'resources/contact-us',
          customProps: {
            icon: '/img/rune/icon/Rune-icon-Contact us.png',
          },
        },
      ],
    },
  ],
};

export default sidebars;
