import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    'landing',
    {
      type: 'category',
      label: 'Rune Docs',
      link: {
        type: 'generated-index',
        title: 'Rune Docs',
        description: 'Documentation for Rune',
        slug: '/category/rune-docs',
      },
      items: [
        {
          type: 'category',
          label: 'Overview',
          collapsible: true,
          collapsed: false,
          items: [
            'rune-documentation/overview/overview',
            'rune-documentation/overview/Quick start',

          ],
        },
        {
          type: 'category',
          label: 'Projects',
          items: [
            'rune-documentation/projects/Projects',
            'rune-documentation/projects/Projects - CDM',
          ],
        },
        {
          type: 'category',
          label: 'Modelling Components',
          link: {
            type: 'doc',
            id: 'rune-documentation/Rune DSL Modelling components',
          },
          items: [
            'rune-documentation/modelling-components/Data',
            'rune-documentation/modelling-components/Metadata',
            'rune-documentation/modelling-components/Expressions',
            'rune-documentation/modelling-components/Data validation',
            'rune-documentation/modelling-components/Function',
            'rune-documentation/modelling-components/Mapping',
            'rune-documentation/modelling-components/Namespace',
            'rune-documentation/modelling-components/Reporting',
          ],
        },
        {
          type: 'category',
          label: 'Developers',
          link: {
            type: 'doc',
            id: 'rune-documentation/developers/Developers',
          },
          items: [
            'rune-documentation/developers/Rune and Java',
            'rune-documentation/developers/Code generator',
            'rune-documentation/developers/Contribute to Rune',
          ],
        },
        {
          type: 'category',
          label: 'Resources',
          items: [
            'rune-documentation/resources/FAQs',
            'rune-documentation/resources/Glossary',
            'rune-documentation/resources/Contact us',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
