import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}], 

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'category',
      label: 'Rune docs',
      link: {
        type: 'generated-index',
        title: 'Rune docs',
        description: 'All you need to know to understand and use the Rune domain-specific language for modelling operational processes in financial and other markets.',
        slug: '/',
      },
      items: [
        {
          type: 'category',
          label: 'Get started',
          description: 'Your introduction to the Rune language.',
          link: {
            type: 'generated-index',
            title: 'Get started',
            description: 'Your introduction to the Rune language.',
            slug: '/rune-documentation/get-started',
          },
          items: [
            'rune-documentation/get-started/index',
            'rune-documentation/get-started/keyword-search',
            'rune-documentation/get-started/overview',
          ],
        },
        {
          type: 'category',
          label: 'Modelling components',
          description: 'Our components and how they work, with examples.',
          link: {
            type: 'generated-index',
            title: 'Modelling components',
            description: 'The Rune DSL can express eight types of model components. This documentation details the purpose and features of each type of model component and highlights their relationships.',
            slug: '/rune-documentation/rune-dsl-modelling-components',
          },
          items: [
            'rune-documentation/modelling-components/data',
            'rune-documentation/modelling-components/metadata',
            'rune-documentation/modelling-components/expressions',
            'rune-documentation/modelling-components/data-validation',
            'rune-documentation/modelling-components/function',
            'rune-documentation/modelling-components/mapping',
            'rune-documentation/modelling-components/namespace',
            'rune-documentation/modelling-components/reporting',
          ],
        },
        {
          type: 'category',
          label: 'Developers',
          description: 'Advanced use of Rune and how you can contribute.',
          link: {
            type: 'generated-index',
            title: 'Developers',
            description: 'Advanced use of Rune and how you can contribute.',
            slug: '/rune-documentation/developers',
          },
          items: [
            'rune-documentation/developers/rune-and-java',
            'rune-documentation/developers/code-generator',
            'rune-documentation/developers/contribute-to-rune',
          ],
        },
        {
          type: 'category',
          label: 'Resources',
          description: 'Our FAQs, glossary, and find out how to get in touch.',
          link: {
            type: 'generated-index',
            title: 'Resources',
            description: 'Our FAQs, glossary, and find out how to get in touch.',
            slug: '/category/resources',
          },
          items: [
            'rune-documentation/resources/faqs',
            'rune-documentation/resources/glossary',
            'rune-documentation/resources/contact-us',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
